config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
     resources :products do
    get 'search', on: :collection
  end
  resources :categories, only: :show do
    resources :products, only: %i[index show]
  end

resources :comments

resources :products do
    resources :order_items, only: %i[create update destroy] do
      member do
        get 'add_quantity'
        get 'remove_quantity'
      end
    end
end

  resources :orders, only: %i[create update destroy] do
      member do
        get 'complete'
      end
    end

    resources :orders, only: :show
  root 'pages#home'
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :product

	validates_presence_of :body, :rating
	validates_uniqueness_of :user_id, scope: :product_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:edit, :update, :destroy]

	def new
		@comment = Comment.new(user_id: params[:user_id], product_id: params[:product_id])
	end

	def create
		@comment = Comment.create(comment_params)

		if @comment.save
			redirect_to product_path(@comment.product)
		else
			flash.now[:error] = @comment.errors.messages
			render  'new'
		end
	end

	def edit; end

	def update
		    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = 'Comment successfully updated!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
        redirect_to @comment.product
  end

  def destroy
    @comment.destroy
     redirect_to @comment.product
	 end

	private

	  def set_comment
    @comment = Comment.find(params[:id])
  end

	def comment_params
		params.require(:comment).permit(:user_id, :product_id, :body, :rating)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_show.html.erb
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<h2 style="text-align: center;">Comments</h2>
<div class="comment">
  <% @product.comments.each do |comment| %>
  <div class="col-lg-10">
    <div class="card shadow mb-5">
      <div class="card-header">
      	<h6><%= comment.user.email %></h6>
        <% comment.rating.times do %>
          <i class="fa fa-star" style="color: #ffde00"></i>
        <% end %>
        <% blank_stars(comment.rating).times do %>
          <i class="fa fa-star" aria-hidden="true" style="color: #e1e1e1"></i>
        <% end %>
      </div>
      <div class="card-body">
        <p class="card-text"><%= comment.body %></p>
        <div style="text-align: center;">
        	 <% if current_user.present? %>
	        	<% if current_user.email == comment.user.email %>
	        		<%= link_to ("Редагувати"), edit_comment_path(comment), class: "btn btn-outline-dark" %>
	            	<%= link_to ("Видалити"), comment_path(comment), method: :delete, class: "btn btn-outline-dark",
	                              data: {confirm: 'Confirm delete your comment?'} %>
	             <% end %>
            <% end %>
         </div>
      </div>

        <div class="row">

        </div>
    </div>
  </div>
<% end %>

  </div>

app/views/comments/_form.html.erb
<div class="container" style="color: white;">
  <div class="pt-5" style="position: relative; top: 40px; left: 50px;">
    <h2> Напишіть ваш відгук </h2>
    <%= form_for @comment do |f| %>
      <% if @comment.errors.any? %>
        <% @comment.errors.full_messages.each do |message| %>
        <h4 class="alert-danger"> <%= message %> </h4>
        <% end %>
      <% end %>
    <div>
      
      <%= f.text_area :body, class: 'form-control', rows: "2" %>
    </div>
    <br>

    <div>
      <p>Ваша оцінка</p>
      <%= f.select :rating, [*1..5], :prompt => 'Select' %>
    </div>
    <br>

    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :product_id %>
    <div><%= f.submit "Оновити коментар", class: "btn btn-outline-light"%></div>
  <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="container">
<div class="form-wrap product-description-details mt-4">
  <h3 class="text-center"> Edit</h3>
  <%= render 'form'%>
</div> 
</div>

app/views/comments/new.html.erb
<div class="container" style="color: white;">
<div class="pt-5" style="position: relative; top: 40px; left: 50px;">
	<h2> Напишіть ваш відгук </h2>
	<%= form_for @comment do |f| %>
		<% if @comment.errors.any? %>
			<% @comment.errors.full_messages.each do |message| %>
			<h4 class="alert-danger"> <%= message %> </h4>
			<% end %>
		<% end %>
	<div>
		<%= f.text_area :body, class: 'form-control', rows: "2" %>
	</div>
	<br>

	<div>
		<p>Ваша оцінка</p>
		<%= f.select :rating, [*1..5], :prompt => 'Select' %>
	</div>
	<br>

	<%= f.hidden_field :user_id %>
	<%= f.hidden_field :product_id %>
	<div><%= f.submit "Створити коментар", class: "btn btn-outline-light"%></div>
<% end %>
</div>
</div>