config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
     resources :products do
    get 'search', on: :collection
  end
  resources :categories, only: :show do
    resources :products, only: %i[index show]
  end

resources :comments

resources :products do
    resources :order_items, only: %i[create update destroy] do
      member do
        get 'add_quantity'
        get 'remove_quantity'
      end
    end
end

  resources :orders, only: %i[create update destroy] do
      member do
        get 'complete'
      end
    end

    resources :orders, only: :show
  root 'pages#home'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  enum status: %i[in_progress ordered canceled]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @items = current_order.order_items
  end

  def  update
    current_product = @order.order_items.find_by(product_id: params[:product_id])

    if current_product.present?
      current_product.update(quantity: current_product.quantity + 1)
    else
      @order.order_items.create.create(product_id: params[:product_id], quantity: 1)
    end

    redirect_to order_path(current_order)
  end

  def complete
     Order.find(params[:id]).update(status: 1)
    OrderMailer.with(user: current_user).complete_order.deliver_now
  end

  private

  def set_current_order
    @order = current_order
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/complete.html.erb
<div class="pt-5" style="position: relative; top: 30px; font: italic small-caps bold 20px/2 cursive; " >
	<div class="jumbotron text-center">
	  <h1 class="display-3" style="font-size: 120px;">ДЯКУЄМО ЗА ПОКУПКУ!</h1>
	  <p class="lead" style="font-size: 60px;"><strong>Перевірте ваш імейл</strong> для того щоб дізнатися як завершити покупку. Гарного дня!.</p>
	  <hr>
	  <p class="lead">
	    <a class="btn btn-outline-dark btn-sm" href="/" role="button" style="font-size: 70px;">Перейти на головну сторінку</a>
	  </p>
	</div>
</div>

app/views/orders/show.html.erb
<main class="container pt-5" style="color: black; font: italic small-caps bold 20px/2 cursive;">
        <div class="row pt-5">
          <div class="col-sm-3 col-12">
                    <nav class="nav flex-column">


<div class="price">
          </nav>
          </div>
          <div class="col-sm-12 col-12">
            <div>
            </div>

<p class="invisible"><%= total_price = 0 %></p>
<div class="col-12">
  <div class="row">
    <% @items.each do |item| %>
    <% total_price += item.product.price * item.quantity%>
        <div class="col-lg-5 col-md-6 mb-4">
          <div class="card h-100">
            <div class="card-body",  style="background-color: grey;">
              <img src="<%= item.product.image %>" class="card-img-top" alt="...">
            </div>
            <div class="card-footer" style="background-color: grey;">
              
              <h5 class="card-title" style="font-size: 30px;"><%= item.product.title %> </h5>
              <p class="card-text text-truncate"><%= item.product.description %></p>
              <p class="badge bg-light text-dark" style="font-size:30px;><%= number_to_currency(item.product.price, unit: "UAH", separator: ",", delimiter: " ", format: "%n %u") %></p>
              <p class="cart-text" style="font-size: 30px;"> Quantity: <%= item.quantity %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

              <%= link_to '↑', add_quantity_product_order_item_path(item.product, item),method: :get, class: "btn btn-default bg-light", style: "font-size: 30px;"%>&nbsp;&nbsp;&nbsp;
              <%= link_to '↓', remove_quantity_product_order_item_path(item.product, item), class: "btn btn-default bg-light", style: "font-size: 30px;", method: :get %>  
              <p></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= link_to 'Remove from cart', product_order_item_path(item.product, item), class: "btn btn-default bg-light", style: "font-size: 30px;", method: :delete%>
            </div>
        </div>
      </div>
<% end%>
<div class="text-center"><%= link_to "Confirm", complete_order_path, class: 'btn btn-outline-light', style: 'font-size: 30px;' %></div>
<h3 style="color: white; font-size: 60px;">Total price: <%= total_price %> </h3>
 </div>
        </div>

      </main><!-- /.container -->