config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
     resources :products do
    get 'search', on: :collection
  end
  resources :categories, only: :show do
    resources :products, only: %i[index show]
  end

resources :comments

resources :products do
    resources :order_items, only: %i[create update destroy] do
      member do
        get 'add_quantity'
        get 'remove_quantity'
      end
    end
end

  resources :orders, only: %i[create update destroy] do
      member do
        get 'complete'
      end
    end

    resources :orders, only: :show
  root 'pages#home'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :categories
  has_many :order_items
  has_many :comments
  validates :title, :price, :description, presence: true

  def self.search(search)
    where('title LIKE ?', "%#{search}%")
  end

     def to_param
    "#{id}-#{title.gsub(/[^a-z0-9]+/i, '-')}"
  end

   def rating
    return 0 if comments.empty?
    comments.sum(&:rating).to_f / comments.count.to_f
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = if params[:search]
                  Product.search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 6)
                else
                  Product.all.order(created_at: :desc).paginate(page: params[:page], per_page: 6)
                end
 if params[:sort] == 'lowPrice'
      @products = Product.order(price: :ASC).paginate(page: params[:page], per_page: 6)
    elsif params[:sort] == 'highPrice'
      @products = Product.order(price: :DESC).paginate(page: params[:page], per_page: 6)
    elsif params[:sort] == 'alphabetAsc'
      @products = Product.order(title: :ASC).paginate(page: params[:page], per_page: 6)
    elsif params[:sort] == 'alphabetDesc'
      @products = Product.order(title: :DESC).paginate(page: params[:page], per_page: 6)
    elsif params[:min] || params[:max]
      @products = Product.where(price: [params[:min]].first..[params[:max]].last).paginate(page: params[:page], per_page: 6)
    end
  end


  def show
    @product = Product.find(params[:id])
            @comment = @product.comments
  end

  
      def avg_rating
    @total_rating = 0
    @comments.each { |r| @total_rating += r.rating }
    @average_rating = (@total_rating.to_f / @comments.count.to_f) if @comments.present?
  end


  def search
    @products = Product.where("name ILIKE ? OR description ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").paginate(page: params[:page], per_page: 6)
    render "products/index"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="col-lg-4 col-md-6 mb-4" >
	<div class="card h-100" style="background-color: grey;">
<%= link_to product do%>
  		<div class="card-body" style="color: black; font: italic small-caps bold 20px/2 cursive; text-decoration: underline; text-decoration-color: grey;">
  		<img src="<%= product.image %>" class="card-img-top" alt="...">
    	<h4><%= product.title%></h4>
    	<p class="card-text text-truncate"><%= product.description%></p>
    	<p class="badge bg-light text-dark" style="font-size:20px;">
    		<%= number_to_currency(product.price, unit: "UAH", separator: ",", delimiter: " ", format: "%n %u") %></p>	    	
    	</div>
<% end%>
	</div>
</div>

app/views/products/index.html.erb
<main class="container pt-5" >
        <div class="row pt-5" >
          <div class="col-sm-4 col-12" >
                    <nav class="nav flex-column" >

                      <% Category.roots.each do |category| %>
                          <%= active_link_to category.title, category_path(category), class: "list-group-item list-group-item-action list-group-item-dark"%>
                            <% if category.has_children? %>
                							<% Category.children_of(category).each do |sub_category| %>
                							<i><%= active_link_to sub_category.title, category_path(sub_category), class: 'list-group-item list-group-item-action list-group-item-warning'%></i>
                						<% end %>
            					<% end %>
                      <% end %>
           <!--<a class="nav-link active" aria-current="page" href="#">Active</a>
            <a class="nav-link" href="#">Link</a>
            <a class="nav-link" href="#">Link</a>
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->


          <div class="input-group mb-3">
      

            <div class="filter-list">
      Sort by price:
      <%= link_to ("From low to high"), products_path(sort: 'lowPrice'), class:'btn-custom-light' %>
      <i>or</i>
      <%= link_to ("From high to low"), products_path(sort: 'highPrice'), class:'btn-custom-light' %>
    </div>
    <div class="filter-list">
      Sort by name:
      <%= link_to ("A-Z"), products_path(sort: 'alphabetAsc'), class:'btn-custom-light' %>
      <i>or</i>
      <%= link_to ("Z-A"), products_path(sort: 'alphabetDesc'), class:'btn-custom-light' %>
    </div>
    <div class="filter-list">
      <%= form_with url: products_path, method: :get, local: true do |form| %>
        <%= form.number_field :min, class: "form-input-number",
                            placeholder: "min price", value:"0"%>
        <%= form.number_field :max, class: "form-input-number",
                            placeholder: "max price" %>
        <%= submit_tag "Filter", class: 'btn btn-outline-dark' do %>
          <i class="fa fa-search" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
</div> 

          <div class="price">
          </nav>
          </div>
          <div class="col-sm-9 col-12">
            <div>
            </div>





<div class="row">
	<%= render @products %>
</div>


<div class="digg_pagination" style="text-align: center;">
    <%= will_paginate @products, :container => false %>
</div>


 </div>
        </div>

      </main><!-- /.container -->

app/views/products/show.html.erb
  </br>
</br>
  <div class="container">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <div class="pt-5">
<section class="mb-5">

  <div class="row" style="color: white; font: italic small-caps bold 20px/2 cursive;">
    <div class="col-md-6 mb-4 mb-md-0">

      <div id="mdb-lightbox-ui"></div>

      <div class="mdb-lightbox">

        <div class="row product-gallery mx-1">

          <div class="col-12 mb-0">
  

                <div class="pt-5">
                <img src="<%= @product.image %>"
                  class="img-fluid z-depth-1">
                  </div>
            
          </div>
        </div>

      </div>

    </div>
    <div class="col-md-6 lefter">
      <div class="pt-5">
      <h5><%= @product.title %></h5>
      <p class="mb-2 text-muted text-uppercase small"><%= @product.category.title %></p>
      <p class="text-muted"> Rating: <%= @product.rating %> </p>

  </div>
      <p class="badge bg-light text-dark"><%= number_to_currency(@product.price, unit: "UAH", separator: ",", delimiter: " ", format: "%n %u") %></p>
      <p class="pt-1"><%= @product.description %></p>
      <div class="table-responsive">
        <table class="table table-sm table-borderless mb-0">

        </table>
      </div>
      <hr>
      <% if current_user.present? %>
    <%= link_to 'Додати до кошика', product_order_items_path(@product), method: :post, class: "btn btn-outline-light"%>
    <% else %>
    <p><%= link_to 'Увійти в систему', new_user_session_path %> для того щаб додати цей продукт до кошика </p>
    <% end %>
    <% if allowed_to_comment(@product) %>
      <%= link_to 'Додати коментар', new_comment_path(user_id: current_user, product_id: @product), method: :get, class: "btn btn-outline-light"%>
      <% end %>


    </div>
  </div>

</section>
<!--Section: Block Content-->
</div>
  <div class="col-lg-12 sm-12">
   <%= render 'comments/comment_show' %>  
  </div>
 </div>